### ISSUE TITLE
banner Display problem

### ISSUE THREAD

**Issue by mry-ship** [yandexmobile/yandex-ads-unity-plugin#57]
<img width="456" alt="image" src="https://user-images.githubusercontent.com/19767759/229188191-72ccafe7-c2a9-4e3a-a41d-6cf9e7fb1e5f.png">

**Comment by mry-ship** [comment]
unity 2020.3.38f1 yandex 2.7.0

**Comment by mry-ship** [comment]
use FlexibleSize type 
set widht
      ScreenUtils.ConvertPixelsToDp(Screen.width);
set height
     Screen.height/10 to DP

**Comment by mobile-ads-github** [comment]
Thanks for your report. Can you give please more details.
What do you mean by display problem? What behaviour is expected and what is actual

Crash logs that you sent unfortunately are not informable, can you please make a debug build, reproduce crash and send us debug stacktrace

**Comment by mry-ship** [comment]
I use the height of the banner to move the UI, but the banner keeps changing；
I tried a 300X50 banner but I also loaded a taller banner to block the ui，

**Comment by mobile-ads-github** [comment]
This issue is not longer reproducible. If it isn't, please reopen this issue.

**Comment by AppMetricaSupport** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 25193727. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp12.07.2023, 12:42, "mobile-ads-github" ***@***.***>:
Closed #57 as completed.

**Comment by AppMetricaSupport** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 25193728. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp12.07.2023, 12:42, "mobile-ads-github" ***@***.***>:
This issue is not longer reproducible. If it isn't, please reopen this issue.
